### ISSUE TITLE
Documentation contributions

### ISSUE THREAD

**Issue by joshrotenberg** [couchbase/docs-sdk-kotlin#2]
Are you accepting contributions for documentation here? I'm doing a little bit of work with the Kotlin SDK and have some spare cycles to help out.

**Comment by RichardSmedley** [comment]
Hi Josh,

Many thanks for the kind offer.

Over the next few months, as we move by steps from DP1 to 1.0 GA, we will be adding a full docs set, such as we have for the other SDKs like https://docs.couchbase.com/java-sdk/current/hello-world/overview.html

We're grateful for any offers of help, and comments on the docs as they develop will be warmly received. 

Let me get back to you properly once we've firmed up the next stage.  :+1: 

Cheers,

      Richard

**Comment by dnault** [comment]
Hi Josh,

I realize it's been a couple months since you reached out, but we haven't forgotten about you. The Kotlin SDK documentation effort will be ramping up soon. If you still have those spare cycles, is there a particular area of the docs you're interested in working on?

Since you're an early adopter, we're also interested in your general feedback on the SDK and where the rough edges might be. A good place for that discussion might be the [Couchbase Forum](https://forums.couchbase.com/c/kotlin-sdk/40) or the #couchbase channel in the [Kotlin Slack workspace](https://surveys.jetbrains.com/s3/kotlin-slack-sign-up).

Thanks,
David

**Comment by RichardSmedley** [comment]
Hello @joshrotenberg 
Always happy to talk about docs contributions - in particular as we're hoping to get more content into the Kotlin SDK docs, to match the others.

However I'm closing this as an issue, as I think David has covered the options in his comment.

All the best, 
   Richard
